### ISSUE TITLE
Scanning preview show half screen Black

### ISSUE THREAD

**Issue by altaf2892** [tarkalabs/EagleScan#1]
**Code**
```
`      BarcodeScannerConfig scannerConfig = new BarcodeScannerConfig.Builder()
                    .barcodeFormats(Barcode.FORMAT_ALL_FORMATS)

                    .showFlashButton(true)
                    .build();
            scanReceiver.launch(scannerConfig, null);
    ActivityResultLauncher<BarcodeScannerConfig> scanReceiver = registerForActivityResult(
            new ScanBarcodeContract(),
            this::handleBarcodeResult);`
```
![issue image](https://github.com/tarkalabs/EagleScan/assets/16555228/384a3e8d-8efe-4022-93d6-e38856abb061) @vagmi @su-docker

**Comment by kalpeshp0310** [comment]
Thanks @altaf2892 for reporting the issue. 
Can you please share more details on this issue, Like - Device, and Android Version? 
Also, would it be possible to share a sample project that simulates the issue?

**Comment by altaf2892** [comment]
![Device Details](https://github.com/tarkalabs/EagleScan/assets/16555228/57624727-dfc0-483b-9959-2c7db97f4ed0) 

>   Code is posted within the question above . Need other device info? let me know

**Comment by altaf2892** [comment]
@kalpeshp0310 CAN I GET the solution?

**Comment by kalpeshp0310** [comment]
Thanks, Altaf for the screenshot, I am trying to get hold of the device. But I am not sure if I will get it. Can you also send me the Android version?

**Comment by altaf2892** [comment]
@kalpeshp0310 it is Android 13.   Realme UI Version : 4.0  @kalpeshp0310  updated

**Comment by kalpeshp0310** [comment]
Thanks Altaf. By any chance do you know your Realmi UI version?, also do you know of any other device that has same issue?

**Comment by kalpeshp0310** [comment]
@altaf2892 I could not get access to the device. Can we pair? Would you be able to share your email address here? I can schedule a call with you and we can debug this together.

**Comment by kalpeshp0310** [comment]
@altaf2892 Are you still facing the issue?

**Comment by altaf2892** [comment]
@kalpeshp0310 issue with **hardwareAccelerated** it was set to false . closing issue
